/* Generated by tools/gen_qr_selftest.py - DO NOT EDIT BY HAND. */
#ifndef QR_SELFTEST_H
#define QR_SELFTEST_H

#include <stdint.h>

/* Embedded known QR codes for on-device quirc verification. */
typedef enum e_qr_selftest_id
{
    QR_SELFTEST_MED001 = 0U,
    QR_SELFTEST_RXORDER = 1U,
    QR_SELFTEST_COUNT = 2U,
} qr_selftest_id_t;

/* Render the embedded QR (centered, quiet zone included in the
 * matrix) into an 8-bit grayscale buffer, white background.
 * No-op on invalid arguments. */
void qr_selftest_render(uint8_t which, uint8_t * p_gray,
                        uint16_t w, uint16_t h);

#endif /* QR_SELFTEST_H */
