#ifndef GUI_GUIDER_LVGL_COMPAT_H
#define GUI_GUIDER_LVGL_COMPAT_H

/* GUI Guider 2.0 emits LVGL 9.4 screen-animation names.  FSP 6.3 supplies
 * LVGL 9.3, where the type is already named lv_screen_load_anim_t but the
 * enumeration constants still use the LV_SCR_LOAD_ANIM_* prefix. */
#include "lvgl.h"

#if (LVGL_VERSION_MAJOR == 9) && (LVGL_VERSION_MINOR < 4)
#define LV_SCREEN_LOAD_ANIM_NONE         LV_SCR_LOAD_ANIM_NONE
#define LV_SCREEN_LOAD_ANIM_OVER_LEFT    LV_SCR_LOAD_ANIM_OVER_LEFT
#define LV_SCREEN_LOAD_ANIM_OVER_RIGHT   LV_SCR_LOAD_ANIM_OVER_RIGHT
#define LV_SCREEN_LOAD_ANIM_OVER_TOP     LV_SCR_LOAD_ANIM_OVER_TOP
#define LV_SCREEN_LOAD_ANIM_OVER_BOTTOM  LV_SCR_LOAD_ANIM_OVER_BOTTOM
#define LV_SCREEN_LOAD_ANIM_MOVE_LEFT    LV_SCR_LOAD_ANIM_MOVE_LEFT
#define LV_SCREEN_LOAD_ANIM_MOVE_RIGHT   LV_SCR_LOAD_ANIM_MOVE_RIGHT
#define LV_SCREEN_LOAD_ANIM_MOVE_TOP     LV_SCR_LOAD_ANIM_MOVE_TOP
#define LV_SCREEN_LOAD_ANIM_MOVE_BOTTOM  LV_SCR_LOAD_ANIM_MOVE_BOTTOM
#define LV_SCREEN_LOAD_ANIM_FADE_IN      LV_SCR_LOAD_ANIM_FADE_IN
#define LV_SCREEN_LOAD_ANIM_FADE_OUT     LV_SCR_LOAD_ANIM_FADE_OUT
#define LV_SCREEN_LOAD_ANIM_OUT_LEFT     LV_SCR_LOAD_ANIM_OUT_LEFT
#define LV_SCREEN_LOAD_ANIM_OUT_RIGHT    LV_SCR_LOAD_ANIM_OUT_RIGHT
#define LV_SCREEN_LOAD_ANIM_OUT_TOP      LV_SCR_LOAD_ANIM_OUT_TOP
#define LV_SCREEN_LOAD_ANIM_OUT_BOTTOM   LV_SCR_LOAD_ANIM_OUT_BOTTOM
#endif

#endif /* GUI_GUIDER_LVGL_COMPAT_H */
