#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the on-device QR self-test sources (qr_selftest.h/.c).

The firmware embeds two known QR codes (a drug code and a pickup-order JSON)
as module matrices.  The QR decode thread renders one into the grayscale
buffer and decodes it, proving quirc works on the M85 without any camera or
optics involved (trigger: Device page "运行自检" button, or J-Link write to
s_dbg_qr_selftest_trigger).

Run:  py tools\\gen_qr_selftest.py
Requires: pip install qrcode  (used with PIL-free matrix API)
"""
import os
import sys
import qrcode

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INC = os.path.join(ROOT, "src", "middleware", "inc", "qr_selftest.h")
SRC = os.path.join(ROOT, "src", "middleware", "src", "qr_selftest.c")

# (enum suffix, payload).  Payloads must stay <= QR_DECODER_PAYLOAD_MAX (128).
CASES = [
    ("MED001", "MED-001"),
    ("RXORDER", '{"oid":"RX-20260818-001","i":[{"id":"MED-001","n":2},{"id":"MED-007","n":1}]}'),
]

def make_matrix(payload):
    qr = qrcode.QRCode(version=None, error_correction=qrcode.constants.ERROR_CORRECT_M,
                       box_size=1, border=4)
    qr.add_data(payload)
    qr.make(fit=True)
    return qr.get_matrix()  # list of rows of bool, includes border quiet zone

def main():
    mats = []
    for name, payload in CASES:
        m = make_matrix(payload)
        mats.append((name, payload, m))
        print(f"{name}: {len(m)}x{len(m)} modules, payload {len(payload)} B")

    with open(INC, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/gen_qr_selftest.py - DO NOT EDIT BY HAND. */\n")
        f.write("#ifndef QR_SELFTEST_H\n#define QR_SELFTEST_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("/* Embedded known QR codes for on-device quirc verification. */\n")
        f.write("typedef enum e_qr_selftest_id\n{\n")
        for i, (name, _, _) in enumerate(mats):
            f.write(f"    QR_SELFTEST_{name} = {i}U,\n")
        f.write(f"    QR_SELFTEST_COUNT = {len(mats)}U,\n")
        f.write("} qr_selftest_id_t;\n\n")
        f.write("/* Render the embedded QR (centered, quiet zone included in the\n")
        f.write(" * matrix) into an 8-bit grayscale buffer, white background.\n")
        f.write(" * No-op on invalid arguments. */\n")
        f.write("void qr_selftest_render(uint8_t which, uint8_t * p_gray,\n")
        f.write("                        uint16_t w, uint16_t h);\n\n")
        f.write("#endif /* QR_SELFTEST_H */\n")

    with open(SRC, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/gen_qr_selftest.py - DO NOT EDIT BY HAND. */\n")
        f.write("#include \"qr_selftest.h\"\n\n")
        f.write("#include <string.h>\n\n")
        f.write("typedef struct\n{\n")
        f.write("    uint8_t        n;       /* matrix size in modules (incl. quiet zone) */\n")
        f.write("    const uint8_t * p_data; /* n*n bytes, row-major, 1=black */\n")
        f.write("} qr_selftest_t;\n\n")
        total = 0
        for name, payload, m in mats:
            n = len(m)
            total += n * n
            f.write(f"/* payload: {payload} */\n")
            f.write(f"static const uint8_t qr_{name.lower()}_matrix[{n}][{n}] = {{\n")
            for row in m:
                f.write("    {" + ",".join("1" if c else "0" for c in row) + "},\n")
            f.write("};\n\n")
        f.write(f"static const qr_selftest_t s_selftests[QR_SELFTEST_COUNT] = {{\n")
        for name, _, m in mats:
            f.write(f"    {{ {len(m)}U, &qr_{name.lower()}_matrix[0][0] }},\n")
        f.write("};\n\n")
        f.write("void qr_selftest_render(uint8_t which, uint8_t * p_gray,\n")
        f.write("                        uint16_t w, uint16_t h)\n{\n")
        f.write("    if ((which >= QR_SELFTEST_COUNT) || (NULL == p_gray) ||\n")
        f.write("        (0U == w) || (0U == h))\n    {\n        return;\n    }\n\n")
        f.write("    const qr_selftest_t * p_selftest = &s_selftests[which];\n")
        f.write("    uint16_t const n = p_selftest->n;\n")
        f.write("    const uint8_t * p_m = p_selftest->p_data;\n\n")
        f.write("    /* white background (slightly off-white like the camera) */\n")
        f.write("    memset(p_gray, 235, (size_t) w * h);\n\n")
        f.write("    /* module size: the matrix already contains the 4-module quiet\n")
        f.write("     * zone, so the QR body spans n modules of min(w,h)/n px */\n")
        f.write("    uint16_t module = (h < w) ? h : w;\n")
        f.write("    module = (uint16_t) (module / n);\n")
        f.write("    if (module < 2U)\n    {\n        module = 2U;\n    }\n\n")
        f.write("    int const x0 = ((int) w - (int) (n * module)) / 2;\n")
        f.write("    int const y0 = ((int) h - (int) (n * module)) / 2;\n\n")
        f.write("    for (uint16_t ry = 0U; ry < n; ry++)\n    {\n")
        f.write("        for (uint16_t rx = 0U; rx < n; rx++)\n        {\n")
        f.write("            if (0U == p_m[(size_t) ry * n + rx])\n            {\n")
        f.write("                continue;    /* white module */\n            }\n")
        f.write("            int const px = x0 + (int) (rx * module);\n")
        f.write("            int const py = y0 + (int) (ry * module);\n")
        f.write("            for (uint16_t dy = 0U; dy < module; dy++)\n            {\n")
        f.write("                int const yy = py + (int) dy;\n")
        f.write("                if ((yy < 0) || (yy >= (int) h))\n                {\n")
        f.write("                    continue;\n                }\n")
        f.write("                uint8_t * p_row = p_gray + (size_t) yy * w;\n")
        f.write("                for (uint16_t dx = 0U; dx < module; dx++)\n                {\n")
        f.write("                    int const xx = px + (int) dx;\n")
        f.write("                    if ((xx < 0) || (xx >= (int) w))\n                    {\n")
        f.write("                        continue;\n                    }\n")
        f.write("                    p_row[xx] = 0U;\n")
        f.write("                }\n            }\n        }\n    }\n}\n")

    print(f"wrote {INC}")
    print(f"wrote {SRC}  (matrix flash ~{total} B)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
