# post_rasc_patch.ps1
# Re-apply manual changes that RASC regeneration overwrites in generated headers.
# Run this AFTER `rasc --generate` (or after any build that re-runs the RASC
# prebuild step).  See docs/RA8P1_工程总览.md -> "RASC 生成后手改项恢复".
#
# NOTE: this file MUST be saved as UTF-8 WITH BOM.  Windows PowerShell 5.1
# treats a BOM-less .ps1 as ANSI (GBK on zh-CN), which would corrupt the UTF-8
# Chinese literals below before they reach the generated headers.
# Do NOT edit this file with tools that strip the BOM; rewrite it via
# PowerShell (WriteAllText + UTF8Encoding($true)) if changes are needed.
#
# Usage:  powershell -NoProfile -ExecutionPolicy Bypass -File tools\post_rasc_patch.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

# Read/write generated headers as UTF-8 without BOM (lv_conf.h is committed BOM-less).
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Read-Utf8([string] $path)
{
    return [System.IO.File]::ReadAllText($path, $utf8NoBom)
}

function Write-Utf8([string] $path, [string] $text)
{
    [System.IO.File]::WriteAllText($path, $text, $utf8NoBom)
}

# ---------------------------------------------------------------------------
# 1. lv_conf.h: LV_MEM_SIZE, LV_USE_FONT_COMPRESSED, LV_USE_TINY_TTF
#    RASC has no properties for these; regeneration wipes the manual blocks.
# ---------------------------------------------------------------------------
$lvConf = Join-Path $root 'ra_cfg\fsp_cfg\lvgl\lvgl\lv_conf.h'
if (Test-Path $lvConf)
{
    $text = Read-Utf8 $lvConf
    $dirty = $false

    # --- 1a. LV_MEM_SIZE 512KB ---
    if ($text.Contains('LV_MEM_SIZE (0x40000)'))
    {
        $memBlock = @'
        /* 512KB：6 个 tiny_ttf 字体 cache 全占满约 200KB+，256KB 曾导致切换
         * 页面后堆耗尽/碎片化（页面卡死 HardFault 的嫌疑根因）。RAM 总量
         * 1.83MB，此处加大到 512KB 留 2 倍余量。 */
        #define LV_MEM_SIZE (0x80000)
'@
        $text = $text.Replace('        #define LV_MEM_SIZE (0x40000)', $memBlock)
        Write-Output 'patched: lv_conf.h LV_MEM_SIZE 256KB->512KB'
        $dirty = $true
    }
    else
    {
        Write-Output 'ok: lv_conf.h LV_MEM_SIZE not the RASC-default 256KB (or already 512KB)'
    }

    # --- 1b. LV_USE_FONT_COMPRESSED + LV_USE_TINY_TTF (one block, HEAD order:
    #         FONT first, then TINY_TTF + FILE_SUPPORT) ---
    if (-not $text.Contains('LV_USE_FONT_COMPRESSED'))
    {
        $marker = '#if LV_USE_DRAW_SW == 1'
        $block = @'
/* Font bitmap RLE compression: frees ~250 KB of flash vs uncompressed glyphs
 * (measured 105 KB -> 38 KB on a 16 px font).  Compressed fonts decode through
 * the LVGL decompress() path where fdsc->stride is 0, so they are independent
 * of the 9.3 stride calculation fix in ra/lvgl.  Enabled for headroom so
 * future runtime characters can be added without overflowing the 1 MB flash.
 * NOTE: RASC regeneration wipes this manual block; re-apply via tools/post_rasc_patch.ps1 */
#ifndef LV_USE_FONT_COMPRESSED
    #define LV_USE_FONT_COMPRESSED (1)
#endif

/* Runtime TrueType font rendering (tiny_ttf): renders arbitrary glyphs from a
 * TTF loaded in RAM / memory-mapped external flash (OSPI CS0 @ 0x80000000).
 * Enables lv_tiny_ttf_create_data() for the "任意文本" path without burning
 * flash per-character.  NOTE: RASC regeneration wipes this manual block;
 * re-apply via tools/post_rasc_patch.ps1 */
#ifndef LV_USE_TINY_TTF
    #define LV_USE_TINY_TTF (1)
#endif
#if LV_USE_TINY_TTF
    #ifndef LV_TINY_TTF_FILE_SUPPORT
        #define LV_TINY_TTF_FILE_SUPPORT (0)
    #endif
#endif

'@
        if ($text.Contains($marker))
        {
            $text = $text.Replace($marker, $block + $marker)
            Write-Output 'patched: lv_conf.h LV_USE_FONT_COMPRESSED + LV_USE_TINY_TTF restored'
            $dirty = $true
        }
        else
        {
            Write-Warning 'lv_conf.h: DRAW_SW marker not found, manual blocks NOT restored'
        }
    }
    else
    {
        Write-Output 'ok: lv_conf.h LV_USE_FONT_COMPRESSED / LV_USE_TINY_TTF already present'
    }

    if ($dirty)
    {
        Write-Utf8 $lvConf $text
    }
}

Write-Output 'post_rasc_patch done.'
