/* AUTO-GENERATED by tools/gen_ospi_icons.py - DO NOT EDIT BY HAND. */
/*
 * Icon pixel data lives in the OSPI icon region
 * (offset 0x950000, mmap 0x80950000, see ICON_FLASH_BASE_OFFSET in ospi_ttf_loader.c).
 * These descriptors replace gui/RA8P1/generated/assets/images/*.c
 * (excluded from the build in CMakeLists.txt) and free ~1002 KB of internal flash.
 */
#include "lvgl.h"

#define OSPI_ICON_REGION_BASE ((const uint8_t *) 0x80950000UL)

const lv_image_dsc_t icon_brand_80x80_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 320,
  .header.flags = 0,
  .header.w = 80,
  .header.h = 80,
  .data_size = 25600,
  .data = OSPI_ICON_REGION_BASE + 0x00000000UL,
};

const lv_image_dsc_t icon_renesas_174x39_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 696,
  .header.flags = 0,
  .header.w = 174,
  .header.h = 39,
  .data_size = 27144,
  .data = OSPI_ICON_REGION_BASE + 0x00006400UL,
};

const lv_image_dsc_t icon_brand_30x30_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 120,
  .header.flags = 0,
  .header.w = 30,
  .header.h = 30,
  .data_size = 3600,
  .data = OSPI_ICON_REGION_BASE + 0x0000CE08UL,
};

const lv_image_dsc_t icon_renesas_108x24_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 432,
  .header.flags = 0,
  .header.w = 108,
  .header.h = 24,
  .data_size = 10368,
  .data = OSPI_ICON_REGION_BASE + 0x0000DC18UL,
};

const lv_image_dsc_t icon_online_24x24_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 96,
  .header.flags = 0,
  .header.w = 24,
  .header.h = 24,
  .data_size = 2304,
  .data = OSPI_ICON_REGION_BASE + 0x00010498UL,
};

const lv_image_dsc_t icon_offline_24x24_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 96,
  .header.flags = 0,
  .header.w = 24,
  .header.h = 24,
  .data_size = 2304,
  .data = OSPI_ICON_REGION_BASE + 0x00010D98UL,
};

const lv_image_dsc_t icon_pickup_order_36x36_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 144,
  .header.flags = 0,
  .header.w = 36,
  .header.h = 36,
  .data_size = 5184,
  .data = OSPI_ICON_REGION_BASE + 0x00011698UL,
};

const lv_image_dsc_t icon_scan_36x36_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 144,
  .header.flags = 0,
  .header.w = 36,
  .header.h = 36,
  .data_size = 5184,
  .data = OSPI_ICON_REGION_BASE + 0x00012AD8UL,
};

const lv_image_dsc_t icon_user_36x36_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 144,
  .header.flags = 0,
  .header.w = 36,
  .header.h = 36,
  .data_size = 5184,
  .data = OSPI_ICON_REGION_BASE + 0x00013F18UL,
};

const lv_image_dsc_t icon_medicine_bottle_56x56_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 224,
  .header.flags = 0,
  .header.w = 56,
  .header.h = 56,
  .data_size = 12544,
  .data = OSPI_ICON_REGION_BASE + 0x00015358UL,
};

const lv_image_dsc_t icon_user_56x56_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 224,
  .header.flags = 0,
  .header.w = 56,
  .header.h = 56,
  .data_size = 12544,
  .data = OSPI_ICON_REGION_BASE + 0x00018458UL,
};

const lv_image_dsc_t icon_password_24x24_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 96,
  .header.flags = 0,
  .header.w = 24,
  .header.h = 24,
  .data_size = 2304,
  .data = OSPI_ICON_REGION_BASE + 0x0001B558UL,
};

const lv_image_dsc_t icon_store_56x56_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 224,
  .header.flags = 0,
  .header.w = 56,
  .header.h = 56,
  .data_size = 12544,
  .data = OSPI_ICON_REGION_BASE + 0x0001BE58UL,
};

const lv_image_dsc_t icon_log_56x56_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 224,
  .header.flags = 0,
  .header.w = 56,
  .header.h = 56,
  .data_size = 12544,
  .data = OSPI_ICON_REGION_BASE + 0x0001EF58UL,
};

const lv_image_dsc_t icon_brand_56x56_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 224,
  .header.flags = 0,
  .header.w = 56,
  .header.h = 56,
  .data_size = 12544,
  .data = OSPI_ICON_REGION_BASE + 0x00022058UL,
};

const lv_image_dsc_t icon_store_48x48_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 192,
  .header.flags = 0,
  .header.w = 48,
  .header.h = 48,
  .data_size = 9216,
  .data = OSPI_ICON_REGION_BASE + 0x00025158UL,
};

const lv_image_dsc_t icon_log_32x32_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 128,
  .header.flags = 0,
  .header.w = 32,
  .header.h = 32,
  .data_size = 4096,
  .data = OSPI_ICON_REGION_BASE + 0x00027558UL,
};

const lv_image_dsc_t icon_nuedc_70x42_ARGB8888 = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 280,
  .header.flags = 0,
  .header.w = 70,
  .header.h = 42,
  .data_size = 11760,
  .data = OSPI_ICON_REGION_BASE + 0x00028558UL,
};

const lv_image_dsc_t boot_photo = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_ARGB8888,
  .header.stride = 2560,
  .header.flags = 0,
  .header.w = 640,
  .header.h = 332,
  .data_size = 849920,
  .data = OSPI_ICON_REGION_BASE + 0x0002B348UL,
};
